export const GET_LOCAL_CUSTOMER = "GET_LOCAL_CUSTOMER";
export const GET_CUSTOMER_FAILED = "GET_CUSTOMER_FAILED";
export const SAVE_LOCAL_CUSTOMER = "SAVE_LOCAL_CUSTOMER";
export const LOG_OUT = "LOG_OUT";

export const SAVE_PRODUCTS = "SAVE_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";