export { default as NavbarTab } from './NavbarTab/NavbarTab';
export { default as SearchInput } from './SearchInput/SearchInput';
export { default as Slider } from './Slider/Slider';
export { default as ProductPanel } from './ProductPanel/ProductPanel';
export { default as CartButton } from './CartComponents/CartButton';
export { default as ProductItem } from './CartComponents/ProductItem';
export { default as PayButton } from './CartComponents/PayButton';
export { default as RemoveButton } from './CartComponents/RemoveBtn';
export { default as Header } from './Header/Header';
export { default as Input } from './Input/Input'